# Content for the Vox Migration Board rebuild. Kept separate from the HTML so
# the page is generated, not hand-maintained — same habit as build_guide.py.
import json

# ── Plain-English glossary ─────────────────────────────────────────────────
GLOSSARY = [
 ("Plex", "The ERP Vox is moving to — the system the factory runs on. Orders, production, inventory and quality records all live in it.",
  "Everything on this page ultimately comes from Plex, or is flagged as something Plex does not hold."),
 ("BigQuery", "Google's data warehouse. Think of it as a very large, very fast spreadsheet that nobody types into by hand.",
  "It sits between Plex and the dashboard. The dashboard never talks to Plex directly."),
 ("PlexTest / PlexProd", "Two separate copies of everything: a practice tenant and the real one. PlexTest is wiped every night at midnight UTC.",
  "A number that looks wrong in test is often just test data. PlexProd is the one that counts at go-live."),
 ("Raw table", "A straight copy of one Plex table, with Plex's own column names. Named raw_ something.",
  "If a raw table is empty, no view built on it can show anything — and that is Plex's side, not ours."),
 ("View", "A saved question asked of the raw tables. It holds no data of its own; it recalculates every time it is read.",
  "Every tile reads a view. Fixing a number usually means editing a view, not re-importing anything."),
 ("Tile", "One box on the scorecard — a number, a bar, a trend line.",
  "One tile can read one view; several tiles often read the same view, filtered differently."),
 ("Row grain", "What one row actually represents: one order, one order line, one shipment, one month.",
  "Mixing grains is the most common way a dashboard quietly doubles a number."),
 ("Aggregation", "The maths applied when many rows become one number — usually sum, average or count.",
  "Summing a percentage instead of averaging it is the classic silent error."),
 ("Blend", "Joining two sources together inside the reporting tool, like a spreadsheet VLOOKUP across two tabs.",
  "Blends are invisible unless someone opens the report — which is how the original audit found broken ones."),
 ("MTD / YTD", "Month-to-date and year-to-date: everything from the 1st of the month, or the 1st of the year, until today.",
  "Every headline figure on the scorecard is one of these two."),
 ("Run rate", "Today's pace projected to the end of the month: what you would finish at if the rest of the month matched so far.",
  "Calendar days, not working days, on this scorecard."),
 ("Sales vs Revenue", "Sales counts an order when it is booked and approved. Revenue counts it when the goods actually ship.",
  "They are deliberately different numbers and will not match. Both are correct."),
 ("Pipeline", "Work that has not become a firm order yet — quotes, and deals still being chased.",
  "Plex knows quotes. It does not know pre-quote deals, so that half stays in Monday.com."),
 ("WIP", "Work in progress: orders that are approved and not yet shipped, valued at the unshipped balance.",
  "Settled 9 Sep: Pending Fulfillment and Hold only. An earlier definition inflated it about 2.4x."),
 ("FPY", "First Pass Yield — the share of units made right the first time, without rework or scrap.",
  "Comes from production records, not from the Quality module. Nothing Quality logs moves this number today."),
 ("DPMO", "Defects Per Million Opportunities — defect rate scaled to a million chances to go wrong.",
  "Needs an 'opportunities per unit' figure. Ours is set to 1 as a placeholder, which makes DPMO and defect rate the same number."),
 ("NC / nonconformance", "A record raised when something is wrong — a batch, a shipment, a complaint. Plex calls it a Problem.",
  "22 real ones exist now, entered by Quality on 18–22 Sep. They are the first real Quality data this project has ever had."),
 ("Problem Form", "The form chosen when an NC is created: Material Destruction, 8D, Risk Assessment, Complaint Form, 5P, CAR…",
  "This is how Quality actually classifies things — more so than any status or category field."),
 ("Deviation", "A documented, approved departure from the normal process. Separate from an NC, though the two can be linked.",
  "Plex's built-in deviation module works; Vox's custom Deviation Form does not submit at all."),
 ("Disposition", "What was decided about the affected material: Scrap, Rework, Return, Use as is, Re-introduce.",
  "Plex has no 'Destroy' — destruction is Scrap. And today the field is blank on every record."),
 ("TAT", "Turnaround time — how long a quality problem took to close.",
  "Measured two ways here: from when it happened, and from when it was written up. The gap is reporting lag."),
 ("Performance / Bonus standard", "The day counts a turnaround is judged against, per stock type. Bonus-bearing.",
  "They live in a table Jennilyn edits directly. Empty in production until the real figures are entered."),
 ("Cycle count", "Spot-checking that a storage location holds what the system says it holds.",
  "Accuracy is a per-location hit rate — each location is right or wrong — not weighted by how much sat in it."),
 ("Out of stock", "A part whose minimum inventory quantity is set, and whose available quantity has gone negative.",
  "The field is Minimum_Inventory_Quantity — not 'minimum stock level', which is what everyone says and no field is called."),
 ("Work centre group", "The production area a machine belongs to: Encapsulating, Bottling, Labeling, Blending, Pre-Weigh…",
  "Plex says Encapsulating where the tile says Encapsulation. An exact-match miss reads as 0% forever, not as an error."),
 ("Sevens and nines", "Part-number families: label parts start with 7, finished goods start with 9.",
  "Part attributes are only ever put on the sevens — which matters for Label Design, not the scorecard."),
 ("Goal scope", "Who a goal applies to: a rep, a work centre group, or the whole company (stored as blank).",
  "Matched to actuals by exact name. A mismatch produces a silent 0%, never an error."),
 ("Monday.com", "The work-management tool Vox uses. Ten tiles are fed from it today.",
  "Most are replaced by Plex; pipeline stays a blend; pre-quote stages stay Monday's for good."),
 ("cGMP", "The FDA's rulebook for how supplements must be made, tested and documented.",
  "It is why Quality tracks yields, deviations and destroyed material so carefully — a regulator can ask at any time."),
 ("S&OP", "Sales & Operations Planning — the recurring negotiation that sets the goals.",
  "It is why no goal can come out of Plex: a target is decided by people, not recorded by a factory."),
]

# ── Tiles ──────────────────────────────────────────────────────────────────
# s  section
# t  tile, in the words people use
# q  the question it answers, plainly
# today  where the number comes from TODAY
# todayst  clean | flagged | broken | monday | manual
# v  our Plex view
# rows  what is in it right now
# kind  real | injected | empty | mixed
# open  what is still unknown, or "" when nothing is
TILES = [
 dict(s="Revenue", t="MTD Revenue", q="How much did we ship and invoice so far this month?",
   today="Vox_Looker_DB — Rev_MTD (Google Sheet, refreshes every 15 min)", todayst="flagged",
   v="sales_revenue_summary_report", rows="1 month", kind="real",
   open="Reads 0 when the tenant holds no shipments — which is a true answer, not a fault."),
 dict(s="Revenue", t="YTD Revenue", q="And how much for the year so far?",
   today="vw_sales (BigQuery view fed from Monday, 4-hour refresh)", todayst="monday",
   v="sales_revenue_summary_report", rows="1 month", kind="real",
   open="Only covers months Plex has. A full year needs a historical top-up from the old system."),
 dict(s="Revenue", t="Revenue by part group", q="Which product families are the revenue actually coming from?",
   today="Not on the dashboard today — new capability", todayst="clean",
   v="sales_revenue_summary_report", rows="1 month", kind="real", open=""),
 dict(s="Revenue", t="Revenue detail (line level)", q="Show me every shipped line behind that total.",
   today="Vox_Looker_DB — Revenue (Google Sheet)", todayst="clean",
   v="shipping_revenue_report", rows="19 lines", kind="injected",
   open="Carries both ship date and invoice date — which one defines the month is still unsettled."),
 dict(s="Revenue", t="% into month & run rate", q="At this pace, where do we land by month end?",
   today="VOX Revenue Targets & Run Rate — Rev_Table (Google Sheet)", todayst="broken",
   v="sales_revenue_run_rate_report", rows="1 month", kind="real",
   open="Calendar days, not business days."),
 dict(s="Revenue", t="Revenue goal & % to goal", q="Are we ahead or behind the number we promised?",
   today="Rev_MTD Goal field (Google Sheet)", todayst="manual",
   v="revenue_vs_goal_report", rows="goal loaded", kind="real",
   open="The 12 monthly figures loaded are the company-wide SALES goal. Revenue and Sales are deliberately different — confirm or retract."),
 dict(s="Revenue", t="Shipping daily — cartons & orders", q="Did the dock move anything yesterday?",
   today="vw_shipping_daily_snapshot (BigQuery) — feeds 7 charts and is currently broken", todayst="broken",
   v="shipping_daily_report", rows="14 days", kind="injected", open=""),
 dict(s="Revenue", t="Total in Shipping / Ready to Ship", q="What is packed and waiting to go out the door?",
   today="Vox_Looker_DB — Flow (Google Sheet)", todayst="clean",
   v="shipping_pending_revenue_report", rows="4 lines", kind="injected",
   open="Counts only the ready quantity, never the whole order. Prices fall back to the customer list when a shipment price is not set yet."),

 dict(s="Sales", t="Sales MTD / YTD", q="How much did we book this month, whether or not it has shipped?",
   today="vw_sales_mtd_vs_goal (Monday-fed BigQuery view)", todayst="monday",
   v="sales_mtd_summary_report", rows="1 month", kind="real",
   open="A sale counts the month the order first reached Pending Fulfillment."),
 dict(s="Sales", t="Sales by rep", q="Who sold it?",
   today="New breakdown of the existing Sales MTD tile", todayst="clean",
   v="sales_mtd_summary_report", rows="1 month", kind="real",
   open="Shows Plex's primary rep. A second rep and a commission split exist in the detail view if credit should be shared."),
 dict(s="Sales", t="Sales goal & % to goal", q="Is each rep tracking to their number?",
   today="vw_sales_mtd_vs_goal · goal field", todayst="manual",
   v="sales_vs_goal_report", rows="69 rep-months", kind="real",
   open="One goal is scoped to the literal text “Sales Representative”, which is not a person and matches nothing."),
 dict(s="Sales", t="Sales detail (line level)", q="Show me the order lines behind the total.",
   today="Not on the dashboard today — new capability", todayst="clean",
   v="sales_mtd_by_status_change_report", rows="39 lines", kind="real", open=""),
 dict(s="Sales", t="Orders pending accounting approval", q="What is sitting with accounting, waiting on a deposit?",
   today="NetSuite parity — not on the Looker scorecard", todayst="clean",
   v="sales_orders_pending_accounting_approval_report", rows="2 orders", kind="real",
   open="Deposit Review confirmed as the accounting stage on 11 Sep. It had been silently dead before that, filtering a status Plex had deleted."),
 dict(s="Sales", t="WIP", q="What is approved, unshipped, and therefore money in flight?",
   today="Vox_Looker_DB — Flow · Phase = WIP (Google Sheet)", todayst="clean",
   v="sales_order_value_by_status_report", rows="33 lines", kind="real",
   open="Any screenshot of this tile from before 9 Sep overstates it by roughly 2.4x."),
 dict(s="Sales", t="Total pipeline", q="What is in play but not yet won?",
   today="vw_pipeline (Monday-fed)", todayst="monday",
   v="pipeline_plex_value_report", rows="24 quote lines", kind="real",
   open="Stays a BLEND on purpose: Plex contributes quotes and pending approvals, Monday contributes everything earlier."),
 dict(s="Sales", t="Opportunities & forecast stages", q="What might become a deal later this quarter?",
   today="vw_pipeline stage values (Monday)", todayst="monday",
   v="", rows="—", kind="empty",
   open="No Plex path, and not meant to have one. Plex tracks quotes and orders, never a deal before it reaches a quote."),

 dict(s="Production", t="Actual vs goal — all areas", q="How much did each area actually make this month?",
   today="Vox_Looker_DB — Production_Daily (Google Sheet) — feeds 21 charts, the most-used source on the whole dashboard", todayst="clean",
   v="production_monthly_by_workcenter_group_report", rows="9 area-months", kind="injected", open=""),
 dict(s="Production", t="Encapsulation / Bottling / Labeling — yesterday", q="Did the line run yesterday, and how much came off it?",
   today="Vox_Looker_DB — Production_Daily (Google Sheet)", todayst="clean",
   v="encap_daily_report · packaging_daily_report · labeling_daily_report", rows="14 days", kind="injected", open=""),
 dict(s="Production", t="Production goals & % to goal", q="Did each area hit its target?",
   today="Vox_Looker_DB — Production_Goals (Google Sheet) — feeds 18 charts", todayst="manual",
   v="production_vs_goal_report", rows="9 rows", kind="injected",
   open="Goals are entered in the Production goals tab of the manual-data form. Group names are read from the report so they always match Plex."),

 dict(s="Quality", t="FPY by area", q="What share of what we made was right the first time?",
   today="Quality_Looker_DB — YTD FPYs (Google Sheet) — feeds 9 charts", todayst="flagged",
   v="quality_fpy_by_area_month_report", rows="9 area-months", kind="injected",
   open="Built from PRODUCTION records, not Quality records — nothing the Quality team logs changes this number today. Is that the definition Vox means?"),
 dict(s="Quality", t="Reworks", q="How many nonconformances were raised, and what happened to the material?",
   today="Vox_Looker_DB — Quality_Rework (Google Sheet)", todayst="clean",
   v="quality_nonconformance_report", rows="22 records", kind="real",
   open="“Rework” exists twice in Plex — a disposition on an NC, and a container inventory status. Different populations; nobody has said which the tile means."),
 dict(s="Quality", t="Deviations", q="What approved departures from process are on record?",
   today="Vox_Looker_DB — Quality_Deviation (Google Sheet)", todayst="clean",
   v="quality_deviation_report", rows="2 deviations", kind="real",
   open="Both are linked to nothing — no job, no part, no problem. Linking them is Quality's next test."),
 dict(s="Quality", t="Destruction $ / Rework $", q="What did the scrapped and reworked material cost us?",
   today="Quality_MatDestr and Quality_Rework (Google Sheets)", todayst="clean",
   v="quality_disposition_cost_report", rows="1 row, $0", kind="real",
   open="Cost is 0.00 on all 22 records and the money is being typed into the description instead — “$2305.57”, “600”, “1.5”. The tile cannot work until that changes."),
 dict(s="Quality", t="30-day rolling TAT", q="How long are quality problems taking to close — and is that good?",
   today="Weekly and Monthly TAT Analysis (Google Sheets)", todayst="flagged",
   v="quality_turnaround_time_report", rows="22 records, 2 closed", kind="real",
   open="Both clocks now ship (from when it happened, and from when it was written up). Which one the Performance/Bonus standards were set against is still unanswered."),

 dict(s="Inventory", t="Quantity available", q="What could we actually promise a customer today?",
   today="Not on the dashboard today — answers the 4 Sep question", todayst="clean",
   v="inventory_available_to_sell_report", rows="121 parts", kind="real",
   open="Use available_vs_total_demand — it includes demand pushed down the bill of materials."),
 dict(s="Inventory", t="Out of stock", q="What are we short of, right now?",
   today="Vox_Looker_DB — Inventory, no status filter (Google Sheet)", todayst="flagged",
   v="inventory_out_of_stock_report", rows="5 parts", kind="real",
   open="Goes to 0 when orders move into Quote status — that is the tile being right, not flaky. A quote is not demand."),
 dict(s="Inventory", t="Top quantity ranking", q="What are we holding the most of?",
   today="vw_top_overstock (BigQuery)", todayst="flagged",
   v="inventory_top_quantity_report", rows="42 parts", kind="real",
   open="Quantity only. A Top Value ranking needs costing, which this tenant does not have."),
 dict(s="Inventory", t="Average daily usage", q="How fast are we burning through each part?",
   today="A raw column on Vox_Looker_DB — Inventory", todayst="flagged",
   v="inventory_avg_daily_usage_report", rows="1 part-month", kind="injected",
   open="Monthly depletion divided by days in the month. Never checked against real movement."),
 dict(s="Inventory", t="Inventory balance (valuation)", q="What is everything in the building worth?",
   today="Flow · Inventory Val phase — never actually built", todayst="broken",
   v="inventory_valuation_total_report", rows="0", kind="empty",
   open="INTERIM ANSWER 16 Sep: pull it from NetSuite for now, while Plex's own costing sits empty. Whether it ever moves to Plex, and by what sync, is still with Accounting."),
 dict(s="Inventory", t="Cycle count accuracy", q="When we spot-check a location, does it hold what the system says?",
   today="Cycle count — Dashboard (Google Sheet), feeds 3 charts and is currently broken", todayst="broken",
   v="part_cycle_count_report", rows="1 month · 9 locations · 82.1%", kind="injected",
   open="Counting is lumpy by design — an empty month is normal, not 0% accuracy. Check locations_counted before showing a percentage."),

 dict(s="Operations", t="Open caps", q="How many capsules are on jobs that are still open?",
   today="Vox_Looker_DB — MFG_Job, no status filter (Google Sheet)", todayst="flagged",
   v="mfg_job_open_caps_report", rows="2 jobs", kind="real",
   open="The original tile had no status filter and over-counted."),
 dict(s="Operations", t="Open bottles", q="And how many bottles?",
   today="Vox_Looker_DB — Bottling_Job (Google Sheet)", todayst="clean",
   v="bottling_job_open_report", rows="9 jobs", kind="real", open=""),
 dict(s="Operations", t="Safe days", q="How long since the last safety incident?",
   today="Vox_Looker_DB — Safety (Google Sheet), currently broken", todayst="broken",
   v="safety_incidents (manual form)", rows="1 test incident", kind="injected",
   open="Plex has no safety-incident object of any kind. An empty log reads as a clean record — which is only true if the log is being kept."),

 dict(s="Operational reports", t="Label Design queue", q="Which orders need artwork, and who do we ask about them?",
   today="NetSuite download → Google Sheet → manual upload to Monday, twice a day", todayst="manual",
   v="label_design_report", rows="3 orders", kind="real",
   open="Not a scorecard tile. Blocked on a Monday licence: the account has CRM, not Work Management."),
]

# ── Open decisions ─────────────────────────────────────────────────────────
FLAGS = [
 dict(q="Should the destruction value go in Plex's Cost field?",
   who="Quality (Sheldon / Jason)", tag="Blocks 3 tiles",
   c="Cost is <b>0.00 on all 22</b> nonconformance records, and the money is being typed into the description instead — three Material Destruction records read <code>$2305.57</code>, <code>600</code> and <code>1.5</code> and nothing else. Destruction $, Rework $ and Deviation $ all read $0 until this changes. We are deliberately not inventing a number."),
 dict(q="Does the scorecard mean the Material Destruction FORM, or the Scrap disposition?",
   who="Quality", tag="Blocks Destruction $",
   c="Vox records a destruction by choosing the <b>Material Destruction form</b> when the record is created. Our tile counts records whose <b>final disposition</b> is Scrap — and that field is blank on all 22, including the one closed record. Both are defensible; they are different populations. We have left the tile on disposition rather than switching quietly."),
 dict(q="Which date did the existing turnaround standards start from?",
   who="Quality", tag="Decides which column the tile reads",
   c="Both clocks now ship — from when the problem happened, and from when it was written up — plus the lag between them. But if the Performance and Bonus standards were set against the written-up date and we report the other, the number runs consistently larger and will look like performance dropped the day Vox switched systems."),
 dict(q="Is there a real opportunities-per-unit figure for DPMO?",
   who="Quality", tag="Feeds 9 charts",
   c="Ours is set to <b>1</b> as a documented placeholder, which makes DPMO and defect rate the same number wearing different labels. Sigma is deliberately not computed from it — a hand-rolled approximation risked being subtly wrong in cGMP-adjacent reporting."),
 dict(q="Is our First Pass Yield what Quality means by FPY?",
   who="Quality", tag="Definition, not data",
   c="We compute good ÷ total from production records. Nothing the Quality team logs touches it. Worth confirming directly — and worth asking whether a <b>deviation</b> should count against yield, or only a standard nonconformance."),
 dict(q="Where does the dollar value of all inventory come from?",
   who="Accounting (via Jennilyn)", tag="Interim answer 16 Sep",
   c="Meaning settled: everything in the building, raw materials through finished goods. <b>Interim source is NetSuite</b> while Plex's costing sits empty — explicitly not permanent. Whether Plex ever gets costed by a one-off upload or an ongoing Celigo sync is still open."),
 dict(q="Who may edit the goals form?",
   who="Jennilyn", tag="Narrowed 21 Sep",
   c="Raised about the turnaround standards, which have since left the form entirely — so what is left to protect is <b>goals</b>. The app is open to anyone in Parasol Group Inc, which is right for a daily activity log and wrong for company targets. It already records who wrote every row, so this is prevention, not attribution."),
 dict(q="Is the Inside Sales role the definitive list of sales reps?",
   who="Jennilyn", tag="Wired, not confirmed",
   c="The goals dropdown now reads Plex's <b>Inside Sales</b> roster — 13 people, including all 7 who currently carry a goal. Before, it listed only reps who had already sold something this month, so a new rep could never be given a target. Outside Sales is deliberately excluded; if BDMs should carry goals too, that is a decision."),
 dict(q="Does the pipeline tile stay a Plex + Monday blend?",
   who="Jennilyn", tag="Two plans on record",
   c="Her own plan from 1 Sep: total pipeline is Monday's figure plus Plex's quotes and pending approvals. That coexists with this project's working assumption that Plex replaces Monday outright. Flagged rather than resolved — it changes what the tile is supposed to show."),
]

# ── The manual forms ───────────────────────────────────────────────────────
FORMS = [
 dict(id="goals", label="Goals — 3 tabs", table="scorecard_goals_app", key="goal type + month + applies-to",
   blurb="Monthly targets, entered on three tabs — Sales goals, Production goals, Revenue goal. Each tab fixes the goal type, so the dropdown is gone: the tab is the choice. One entry can fill a run of months, so a year is set in one go.",
   fields=[("(Goal type)","set by tab","Sales, Production or Revenue — no longer asked for"),
           ("Month","month","Always the 1st; reports group by month"),
           ("Applies to","dropdown","A rep, a work centre group, or (company-wide). The list is read from the reports, never typed — Plex says Encapsulating where the tile says Encapsulation, and a mismatch reads as 0% forever"),
           ("Goal","money","required"),
           ("Apply to how many months?","number","1–24; each month is written as its own row"),
           ("Note","long text","optional")],
   note="Shows what is already saved above the fields, with who last changed it — so nobody overwrites December's goal without seeing it first."),
 dict(id="incidents", label="Safety incidents", table="safety_incidents", key="date + area + type",
   blurb="One row per incident. Days without an incident counts forward from the newest row.",
   fields=[("Date of incident","date","no future dates"),
           ("Area","dropdown","Work centre groups from the production report, plus Other"),
           ("Type","dropdown","Injury / Near miss / Property damage / Spill or release / Other"),
           ("OSHA recordable?","dropdown","Yes / No"),
           ("Days lost","number","optional"),
           ("What happened","long text","required")],
   note="Plex has no safety-incident object at all — this form is the only source. It now shows the most recent incident above the fields, and says “no incidents logged yet” in as many words, because a blank and a clean record are not the same claim."),
]

TABLES = [
 dict(name="turnaround_standards", who="Jennilyn, directly in BigQuery",
   what="Performance and Bonus day counts per stock type — what turnaround actuals get judged against.",
   state="Created in both datasets 22 Sep. <b>Empty in production</b> until the real figures are entered; test holds three clearly-labelled placeholders.",
   warn="Must exist or the turnaround report fails to create — and it fails looking like a broken report, not a missing table. Empty is fine."),
 dict(name="scorecard_goals_app", who="The manual-data web app, through its Google Sheet",
   what="Every goal anyone enters on the form.",
   state="12 revenue goals live. The 68 real sales goals still sit in the old table until someone runs the one-click import.",
   warn="Rebuilt from the sheet on every save, so writing to it directly does nothing that survives."),
]

RECENT = [
 ("22 Sep", "Every Quality report was reading the wrong Plex table", "Vox records on Plex's UX screen, which writes a different table than the one we read. 19 records visible in the UI, 0 in the table we queried. Four reports had returned 0 rows since the day they were built, while every job reported success. Repointed — 22 records now flow through."),
 ("22 Sep", "Cycle count was unqueryable, not empty", "It had been recorded as “0 rows, nothing counted yet”. It was actually failing to parse, because it cast a date type BigQuery refuses to convert. A row-count status check cannot tell those two apart."),
 ("22 Sep", "One goals pipeline instead of two", "Six views and two sources collapsed to three views and one. A goal entered in the web app never reached the main tiles before — you had to know to look at a parallel “v2” copy."),
 ("22 Sep", "Turnaround standards have a home", "A table Jennilyn edits directly, joined per stock type with a catch-all for records with no part. Met/missed is blank rather than false while a record is open."),
 ("22 Sep", "A test-data injector", "Puts rows under the tiles on demand and removes them on demand, so a blank tile can be told apart from a broken one. It is what found the cycle-count bug."),
]

if __name__ == "__main__":
    print(json.dumps(dict(glossary=GLOSSARY, tiles=TILES, flags=FLAGS,
                          forms=FORMS, tables=TABLES, recent=RECENT)))
